server:
  port: 8082
  servlet:
    context-path: /parking
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/parking?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.jdbc.Driver

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs

mybatis:
  type-aliases-package: com.park.entity            # 定义所有操作类的别名所在包
  mapper-locations: classpath:mapper/**/*.xml     # 所有的mapper映射文件
  configuration:
    map-underscore-to-camel-case: false

app:
  appSecret: 1ecd0107d68488ed971b7441d7dfd5da
  parkInfoListUrl: http://open.6api.net/parking/ParkInfoList
  nearbyParkInfoUrl: http://open.6api.net/parking/NearbyParkInfoList
  queryParkInfoUrl: http://open.6api.net/parking/queryParkInfoById